name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telnetlib3  # або інші залежності

    - name: Run testscript_task.py
      run: python $GITHUB_WORKSPACE/testscript_task.py --address 3.84.140.235 --port 8888 --timeout 15

    - name: Check script output for success
      run: grep -q "Port is open" $GITHUB_WORKSPACE/testscript_task.py && echo "Port is open" || echo "Port is not available"
